receivers:
  otlp:
    protocols:
      grpc:
exporters:
  debug:
    verbosity: detailed
processors:
  batch:
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
