apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-otel-collector-config
  namespace: benchmark
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      debug:
        verbosity: detailed
    processors:
      batch:
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [debug]
          processors: [batch]

  