apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  cpu:
    isolated: 4-31,36-63
    reserved: 0-3,32-35
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
  additionalKernelArgs:
  - iommu=pt
  - intel_iommu=on
  - nmi_watchdog=0
  - audit=0
  - mce=off
  - processor.max_cstate=1
  - idle=poll
  - intel_idle.max_cstate=0
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: "" 
  net:
    userLevelNetworking: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: "single-numa-node"
  realTimeKernel:
    enabled: false 
