apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
  annotations:
    kubeletconfig.experimental: "{\"cpuManagerPolicyOptions\": {\"full-pcpus-only\": \"true\"}}"
spec:
  cpu:
    isolated: 4-31,36-63
    reserved: 0-3,32-35
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
  additionalKernelArgs:
  - iommu=pt
  - intel_iommu=on
  - "rcupdate.rcu_normal_after_boot=0"
  - "efi=runtime"
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: "" 
  net:
    userLevelNetworking: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: restricted
  realTimeKernel:
    enabled: false 
