apiVersion: v1
kind: Pod
metadata:
  name: opentelemetry-collector
  labels:
    app: opentelemetry-collector
  namespace: benchmark
spec:
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        name: cm-otel-collector-config
  containers:
  - name: opentelemetry-collector
    image: docker.io/otel/opentelemetry-collector
    volumeMounts:
    - name: config-volume
      mountPath: /etc/otel-collector-config.yaml
      subPath: otel-collector-config.yaml
    args:
      - "--config=/etc/otel-collector-config.yaml"
    ports:
      - containerPort: 4317
  nodeSelector:
    node-role.kubernetes.io/master: ""
