apiVersion: v1 
kind: Pod 
metadata:
  name: testpmd
  labels:
    app: testpmd
  namespace: benchmark 
  annotations:
    k8s.v1.cni.cncf.io/networks: >
      [
         {
           "name": "sriov-west",
           "mac": "00:11:22:33:00:00",
           "namespace": "default"
         },
         {
           "name": "sriov-east",
           "mac": "00:11:22:33:00:11",
           "namespace": "default"
         }
      ]
    cpu-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
spec:
  runtimeClassName: performance-performance
  restartPolicy: Never
  volumes:
    - name: devpages
      emptyDir:
        medium: HugePages
    - name: vfio
      hostPath:
        path: /dev/vfio
        #type: Directory
    - name: lib-firmware
      hostPath:
        path: /lib/firmware
    - name: dpdk
      emptyDir: {}
  containers:
  - name: flexran-du 
    image: quay.io/jianzzha/testpmd:22.11.2
    imagePullPolicy: Always
    volumeMounts:
    - name: devpages 
      mountPath: /dev/hugepages
    - name: vfio
      mountPath: /dev/vfio
    - name: lib-firmware
      mountPath: /lib/firmware
    - name: dpdk
      mountPath: /var/run/dpdk
    command:
      - "/root/runner"
      - "--auto"
    resources:
      limits:
        cpu: "6"
        hugepages-1Gi: 2Gi
        memory: 1Gi 
        openshift.io/intelnics0: "1"
        openshift.io/intelnics1: "1"
      requests:
        cpu: "6"
        hugepages-1Gi: 2Gi
        memory: 1Gi 
        openshift.io/intelnics0: "1"
        openshift.io/intelnics1: "1"
    securityContext:
        privileged: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
