apiVersion: v1
kind: Service
metadata:
  labels:
    app: opentelemetry-collector 
  name: opentelemetry-collector 
  namespace: benchmark
spec:
  ports:
  - port: 4317
    protocol: TCP
    targetPort: 4317
    name: opentelemetry-collector
  selector:
    app: opentelemetry-collector
  sessionAffinity: None

