apiVersion: v1
kind: Service
metadata:
  labels:
    app: dpdk-telemetry
  name: dpdk-telemetry
  namespace: benchmark
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
    name: dpdk-telemetry
  selector:
    app: dpdk-telemetry
  sessionAffinity: None
  type: NodePort 

