FROM registry.access.redhat.com/ubi9/ubi-minimal:9.1 as dpdk-builder
ARG VER=22.11.2
USER root
RUN microdnf install -y tar xz python3 python3-pip gcc \
             kernel-devel kernel-headers libcap-devel libpcap-devel \
             numactl-devel libibverbs rdma-core
RUN pip3 install meson ninja pyelftools
RUN curl -L -o dpdk.tar.xz https://fast.dpdk.org/rel/dpdk-$VER.tar.xz && \
    mkdir -p /opt/dpdk && tar -xf dpdk.tar.xz && \
    cp -r dpdk*/* /opt/dpdk/ && \
    pushd /opt/dpdk && \ 
    rm -rf build && \
    meson setup --default-library=static build && cd build && ninja && \
    install -t /usr/local/bin app/dpdk-testpmd
