FROM registry.access.redhat.com/ubi9/ubi-minimal:9.1.0-1829 as dpdk-builder
ARG VER=22.11.2
USER root
RUN microdnf install -y tar xz python3 python3-pip gcc \
             kernel-devel kernel-headers libcap-devel libpcap-devel \
             numactl-devel libibverbs rdma-core
RUN pip3 install meson ninja pyelftools
RUN curl -L -o dpdk.tar.xz https://fast.dpdk.org/rel/dpdk-$VER.tar.xz && \
    mkdir -p /opt/dpdk && tar -xf dpdk.tar.xz && \
    cp -r dpdk*/* /opt/dpdk/ && \
    pushd /opt/dpdk && \
    rm -rf build && \
    meson setup --default-library=static -Dplatform=generic build && cd build && ninja && \
    install -t /usr/local/bin app/dpdk-testpmd

FROM golang:1.20.5 as gobuilder
COPY . /build
WORKDIR /build/cmd
ENV GO111MODULE=on
RUN CGO_ENABLED=0 GOOS=linux go build -o runner

FROM registry.access.redhat.com/ubi9/ubi-micro:9.1.0-17
USER root
COPY --from=gobuilder /build/cmd/runner /root/runner
COPY --from=dpdk-builder /usr/local/bin/dpdk-testpmd /usr/bin/testpmd
COPY --from=dpdk-builder /lib64/libelf-0.188.so /lib64/libelf-0.188.so
COPY --from=dpdk-builder /lib64/libpcap.so.1.10.0 /lib64/libpcap.so.1.10.0
COPY --from=dpdk-builder /lib64/libm.so.6 /lib64/libm.so.6
COPY --from=dpdk-builder /lib64/libcrypto.so.3.0.1 /lib64/libcrypto.so.3.0.1
COPY --from=dpdk-builder /lib64/libz.so.1.2.11 /lib64/libz.so.1.2.11
COPY --from=dpdk-builder /lib64/libc.so.6 /lib64/libc.so.6
COPY --from=dpdk-builder /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=dpdk-builder /lib64/libibverbs.so.1.14.44.0 /lib64/libibverbs.so.1.14.44.0
COPY --from=dpdk-builder /lib64/libnl-route-3.so.200.26.0 /lib64/libnl-route-3.so.200.26.0
COPY --from=dpdk-builder /lib64/libnl-3.so.200.26.0 /lib64/libnl-3.so.200.26.0
COPY --from=dpdk-builder /lib64/libgcc_s-11-20221121.so.1 /lib64/libgcc_s-11-20221121.so.1
COPY --from=dpdk-builder /lib64/libnuma.so.1.0.0 /lib64/libnuma.so.1.0.0
RUN cd /lib64 && ln -sfT libelf-0.188.so libelf.so.1 && \
    ln -sfT libpcap.so.1.10.0 libpcap.so.1 && \
    ln -sfT libcrypto.so.3.0.1 libcrypto.so.3 && \
    ln -sfT libz.so.1.2.11 libz.so.1 && \
    ln -sfT libibverbs.so.1.14.44.0 libibverbs.so.1 && \
    ln -sfT libnl-route-3.so.200.26.0 libnl-route-3.so.200 && \
    ln -sfT libnl-3.so.200.26.0 libnl-3.so.200 && \
    ln -sfT libgcc_s-11-20221121.so.1 libgcc_s.so.1 && \
    ln -sfT libnuma.so.1.0.0 libnuma.so.1
WORKDIR /root
ENTRYPOINT ["/root/runner"]


